# Generated by Django 3.1.4 on 2021-01-08 16:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AlumniInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('r_no', models.BigIntegerField(default=None)),
                ('email', models.EmailField(max_length=254)),
                ('course', models.CharField(default=None, max_length=20)),
                ('m_no', models.BigIntegerField()),
                ('org_name', models.CharField(default=None, max_length=100)),
                ('org_add', models.CharField(default=None, max_length=100)),
                ('al_dsg', models.CharField(default=None, max_length=50)),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to='')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
