# Generated by Django 3.1.4 on 2021-01-09 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Alumni_Interface', '0003_auto_20210109_1542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumniinfo',
            name='profile_pic',
            field=models.ImageField(blank=True, default='default.png', null=True, upload_to=''),
        ),
    ]
